# Optional overrides to route credentials into services and enable Grafana OIDC via Keycloak.
# Also fixes node-exporter mount propagation issues on WSL2 and private-root environments.
services:
  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-${GRAFANA_ADMIN_USER:-admin}}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-${GRAFANA_ADMIN_PASSWORD:-admin}}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_SIGNOUT_REDIRECT_URL=${KC_BASE_URL:-http://localhost:8089}/realms/${KC_REALM_NAME:-AIOPS}/protocol/openid-connect/logout
      - GF_AUTH_GENERIC_OAUTH_ENABLED=${GF_AUTH_GENERIC_OAUTH_ENABLED:-true}
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${KC_GRAFANA_CLIENT_ID:-grafana}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${KC_GRAFANA_CLIENT_SECRET:-}
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${KC_BASE_URL:-http://localhost:8089}/realms/${KC_REALM_NAME:-AIOPS}/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${KC_BASE_URL:-http://localhost:8089}/realms/${KC_REALM_NAME:-AIOPS}/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=${KC_BASE_URL:-http://localhost:8089}/realms/${KC_REALM_NAME:-AIOPS}/protocol/openid-connect/userinfo
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-http://localhost:3000/}
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "30m"

  clickhouse:
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-clickhouse123}
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "30m"

  # Node Exporter - Override for WSL2/private-root mount compatibility
  node-exporter:
    volumes:
      - '/:/host:ro,rslave'  # Use rprivate instead of rslave to avoid bind propagation issues
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.disable-exporter-metrics'  # Reduce noise in metrics
      - '--collector.disable-defaults'   # Disable collectors that may fail on limited filesystems
      - '--collector.cpu'                # Enable only essential collectors  
      - '--collector.meminfo'
      - '--collector.filesystem'
      - '--collector.loadavg'
      - '--collector.time'
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "30m"

  vector:
    image: timberio/vector:0.49.0-debian
    volumes:
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/messages:/var/log/messages:ro
      - /var/log/sample/:/var/log/sample/:ro
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-admin}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-admin}
      - VECTOR_LOG=trace
    ports:
      - "8686:8686"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "30m"
