services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data: {}