apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoria-metrics
    url: http://victoria-metrics:8428
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1

  - name: ClickHouse HTTP
    type: prometheus
    uid: clickhouse
    url: http://clickhouse:8123
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "30s"
      httpMethod: GET
    version: 1