apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoria-metrics
    url: http://victoria-metrics:8428
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1