apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoria-metrics
    url: http://victoria-metrics:8428
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse:8123
    access: proxy
    isDefault: false
    editable: true
    database: "logs"
    basicAuth: true
    basicAuthUser: "${CLICKHOUSE_USER:-default}"
    secureJsonData:
      basicAuthPassword: "${CLICKHOUSE_PASSWORD:-clickhouse123}"
    jsonData:
      defaultDatabase: "logs"
      username: "${CLICKHOUSE_USER:-default}"
    version: 1