global:
  scrape_interval: 15s

scrape_configs:
  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # NATS monitoring
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    scrape_interval: 30s
    metrics_path: /varz

  # VictoriaMetrics self-monitoring
  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['victoria-metrics:8428']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: /metrics

  # Network Device Collector metrics
  - job_name: 'network-device-collector'
    static_configs:
      - targets: ['network-device-collector:8080']
    scrape_interval: 30s
    metrics_path: /metrics