[api]
enabled = true
address = "0.0.0.0:8686"

[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 10

[sources.syslog]
type = "syslog"
address = "0.0.0.0:1514"
mode = "tcp"

[sources.file_logs]
type = "file"
include = ["/var/log/sample/*.log"]
read_from = "beginning"

[transforms.metrics_for_logs]
type = "remap"
inputs = ["host_metrics"]
source = '''
counter_val = if exists(.counter) { .counter.value } else { null }
gauge_val = if exists(.gauge) { .gauge.value } else { null }

. = {
  "timestamp": format_timestamp!(.timestamp, format: "%Y-%m-%d %H:%M:%S%.3f"),
  "level": "INFO", 
  "message": "Host metric collected: " + to_string!(.name),
  "source": "host_metrics",
  "host": "ship-01",
  "service": "system-monitor", 
  "raw_log": encode_json(.),
  "labels": .tags,
  "name": to_string!(.name),
  "namespace": to_string!(.namespace),
  "tags": .tags,
  "kind": to_string!(.kind),
  "counter_value": counter_val,
  "gauge_value": gauge_val
}
'''

[transforms.syslog_for_logs]
type = "remap"  
inputs = ["syslog"]
source = '''
.timestamp = .timestamp
.level = "INFO"
.message = .message
.source = "syslog"
.host = if exists(.hostname) { .hostname } else { "unknown" }
.service = if exists(.appname) { .appname } else { "system" }
.raw_log = encode_json(.)
.labels = {}
.name = ""
.namespace = ""
.tags = {}
.kind = ""
.counter_value = null
.gauge_value = null
'''

[transforms.file_logs_processed]
type = "remap"
inputs = ["file_logs"]
source = '''
.timestamp = .timestamp
.level = .level
.message = .message
.source = "file"
.host = .host
.service = .service
.raw_log = encode_json(.)
.labels = if exists(.labels) { .labels } else { {} }
.name = ""
.namespace = ""
.tags = {}
.kind = ""
.counter_value = null
.gauge_value = null
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["metrics_for_logs"]
endpoint = "http://clickhouse:8123"
table = "raw"
database = "logs"
compression = "gzip"
skip_unknown_fields = true
batch.max_events = 1
batch.timeout_secs = 1
healthcheck.enabled = true

# Debug sink to see ONLY transformed data
[sinks.transform_debug]
type = "console"
inputs = ["metrics_for_logs"]
target = "stdout"
encoding.codec = "json"

# Disable the regular console debug to avoid confusion
# [sinks.console_debug]
# type = "console"  
# inputs = ["metrics_for_logs"]
# target = "stdout"
# encoding.codec = "json"

