[api]
enabled = true
address = "0.0.0.0:8686"

[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 10

[transforms.metrics_for_logs]
type = "remap"
inputs = ["host_metrics"]
source = '''
.timestamp = .timestamp
.level = "INFO"
.message = .name
.source = "host_metrics"
.host = if exists(.tags) && exists(.tags.host) { .tags.host } else { "unknown" }
.service = if exists(.tags) && exists(.tags.collector) { .tags.collector } else { "metrics" }
.raw_log = encode_json(.)
.labels = if exists(.tags) { .tags } else { {} }
.name = .name
.namespace = .namespace
.tags = if exists(.tags) { .tags } else { {} }
.kind = .kind
.counter_value = if exists(.counter) { .counter.value } else { null }
.gauge_value = if exists(.gauge) { .gauge.value } else { null }
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["metrics_for_logs"]
endpoint = "http://clickhouse:8123"
table = "raw"
database = "logs"
compression = "gzip"
skip_unknown_fields = true
batch.max_events = 1
batch.timeout_secs = 1

[sinks.clickhouse.auth]
strategy = "basic"
user = "admin"
password = "admin"

