[api]
enabled = true
address = "0.0.0.0:8686"

[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 10

[sources.syslog]
type = "syslog"
address = "0.0.0.0:1514"
mode = "tcp"

[sources.file_logs]
type = "file"
include = ["/var/log/sample/*.log"]
read_from = "beginning"

[transforms.metrics_for_logs]
type = "remap"
inputs = ["host_metrics"]
source = '''
.timestamp = .timestamp
.level = "INFO"
.message = .name
.source = "host_metrics"
.host = if exists(.tags) && exists(.tags.host) { .tags.host } else { "unknown" }
.service = if exists(.tags) && exists(.tags.collector) { .tags.collector } else { "metrics" }
.raw_log = encode_json(.)
.labels = if exists(.tags) { .tags } else { {} }
.name = .name
.namespace = .namespace
.tags = if exists(.tags) { .tags } else { {} }
.kind = .kind
.counter_value = if exists(.counter) { .counter.value } else { null }
.gauge_value = if exists(.gauge) { .gauge.value } else { null }
'''

[transforms.syslog_for_logs]
type = "remap"  
inputs = ["syslog"]
source = '''
.timestamp = .timestamp
.level = "INFO"
.message = .message
.source = "syslog"
.host = if exists(.hostname) { .hostname } else { "unknown" }
.service = if exists(.appname) { .appname } else { "system" }
.raw_log = encode_json(.)
.labels = {}
.name = ""
.namespace = ""
.tags = {}
.kind = ""
.counter_value = null
.gauge_value = null
'''

[transforms.file_logs_processed]
type = "remap"
inputs = ["file_logs"]
source = '''
.timestamp = .timestamp
.level = .level
.message = .message
.source = "file"
.host = .host
.service = .service
.raw_log = encode_json(.)
.labels = if exists(.labels) { .labels } else { {} }
.name = ""
.namespace = ""
.tags = {}
.kind = ""
.counter_value = null
.gauge_value = null
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["metrics_for_logs"]
endpoint = "http://clickhouse:8123"
table = "raw"
database = "logs"
compression = "gzip"
skip_unknown_fields = true
batch.max_events = 1
batch.timeout_secs = 1

# Add a debug sink to console to see what data is being sent
[sinks.console_debug]
type = "console"
inputs = ["metrics_for_logs"]
target = "stdout"
encoding.codec = "json"

[sinks.clickhouse.auth]
strategy = "basic"
user = "default"
password = "changeme_clickhouse"

