apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-naas-v03
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iLodeStar/AIOps-NAAS
    targetRevision: HEAD
    path: k8s/overlays/ship
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops-naas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10